### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by Binner-Done** [rodymol123/MaterialCraft#4]
Hi,
I don't understand how to install this,
Thanks

**Comment by rodymolenaar** [comment]
You pick the version you want from [here](https://github.com/rodymol123/MaterialCraft/tree/master/dist)

For example the default version [here](https://github.com/rodymol123/MaterialCraft/blob/master/dist/materialcraft.css)

And copy the contents of that file into your webstore's theme section.
