### ISSUE TITLE
Add license to LICENSE.md

### ISSUE THREAD

**Issue by rafaelklaessen** [rodymol123/MaterialCraft#5]
Instead of putting it at the bottom of your readme, you could also put your license in LICENSE.md. This will also make Github show it in the header (next to contributors).

**Comment by rodymolenaar** [comment]
Done in e76bac431a8388c0216715775a800765d0e9a3bf

Thanks for the tip! :)

**Comment by rafaelklaessen** [comment]
If you'd name the commit `fixed #5 Blah`, it'd automatically close the issue.

**Comment by rodymolenaar** [comment]
I know that... just as I pressed enter :')

Psst... Nederlanders onder elkaar :P
